### ISSUE TITLE
stationary or moving FWH control surface

### ISSUE THREAD

**Issue by xiaoerzhang** [weiqishen/FWH#1]
Hi Weiqi, I am learning FWH model and luckily found your codes which are very helpful for me to understand the model. 

By comparing your codes and Farassat Formulation 1A, I am confused that your code is for stationary or moving surface. It looks like you are using a stationary surface but you have a variable Machr in your formulation. However it is defined as ur_tau/sound speed not the velocity of moving surface/sound speed. Could you please explain that if your code is for stationary surface and which formulation you are referring to? Thank you very much

**Comment by weiqishen** [comment]
Hi, xiaoerzhang. The mach number refers to that of the fluid. The surface is always stationary in this code. For details of the formulation, you can go to the section 2.2 of Lyrintzis’s paper and section 2.3 of my paper. Thank you.
[ws-jtca_Shen.pdf](https://github.com/weiqishen/FWH/files/5725840/ws-jtca_Shen.pdf)
[lyrintzis2003FWH.pdf](https://github.com/weiqishen/FWH/files/5725850/lyrintzis2003FWH.pdf)

**Comment by xiaoerzhang** [comment]
Thank you Weiqi for your explanation. It is really helpful.

**Comment by BenjaminDai** [comment]
Hi, Weiqi,
   I successfully complied your code on my PC with Ubuntu18.04, thanks for sharing.  There is a question about how to use this code to do computation. Could you explain what kind of data file does this code read in, or how to use this code with other CFD software? Thanks.
